# add the following to _config.yml file
title: Lucas Ben
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
navigation:
- title: Home
  url: /
- title: My Projects
  url: /projects/
- title: School
  url: /school/
